### ISSUE TITLE
.vue support

### ISSUE THREAD

**Issue by extraymond** [lowlevelm/Bulma-autocomplete-2#1]
Hi! It would be nice to have autocomplete support for .vue  (vue component file)

The format is .text.html.vue

**Comment by lowlevelm** [comment]
Hello! is vue a javascript library? if so, this is only for the bulma css library and font awesome. but if vue is a file type, i could definitely integrate it! Thanks for your feedback.

**Comment by extraymond** [comment]
Hi! Vue collects all html(or pug...), javascript(or typescript) and css(or sass) in a single file called vue component, therefore autocomplete for html tags will benefit vue workflow too.

It looks like this!
[vue coponent](https://vuejs.org/v2/guide/single-file-components.html)

**Comment by lowlevelm** [comment]
Hello, i cannot find a grammar for vue.js. the html grammar looks like this: .text.html.basic
do you have a plugin installed for vue?

**Comment by extraymond** [comment]
You will need [language-vue](https://atom.io/packages/language-vue) first I think!

**Comment by lowlevelm** [comment]
Alright, i will get working on the patch as soon as possible. Thank you for helping to make my plugin better!

**Comment by extraymond** [comment]
No biggie! Thank your for making my life better~

**Comment by lowlevelm** [comment]
Since I have changed my github username, atom isn't letting me update my package. this feature will be in the next update as soon as atom fixes this issue

**Comment by lowlevelm** [comment]
Finally got the time to fix this. I forgot to say, vue support was added, and the plugin is updated to the current version on atom.
